spring:
  profiles:
    active: dev
  application:
    name: tracker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.globally_quoted_identifiers: true
    defer-datasource-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  sql:
    init:
      mode: always

info:
  app:
    name: "tracker"
    description: "Tracker Service"
    version: 1.0.0

logging:
  level:
    com:
      proj:
        tracker: DEBUG

server:
  port: 8080
